// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/v1/group/service.proto

package groupconnect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	group "github.com/rigdev/rig-go-api/api/v1/group"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// ServiceName is the fully-qualified name of the Service service.
	ServiceName = "api.v1.group.Service"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ServiceCreateProcedure is the fully-qualified name of the Service's Create RPC.
	ServiceCreateProcedure = "/api.v1.group.Service/Create"
	// ServiceDeleteProcedure is the fully-qualified name of the Service's Delete RPC.
	ServiceDeleteProcedure = "/api.v1.group.Service/Delete"
	// ServiceListProcedure is the fully-qualified name of the Service's List RPC.
	ServiceListProcedure = "/api.v1.group.Service/List"
	// ServiceUpdateProcedure is the fully-qualified name of the Service's Update RPC.
	ServiceUpdateProcedure = "/api.v1.group.Service/Update"
	// ServiceGetProcedure is the fully-qualified name of the Service's Get RPC.
	ServiceGetProcedure = "/api.v1.group.Service/Get"
	// ServiceAddMemberProcedure is the fully-qualified name of the Service's AddMember RPC.
	ServiceAddMemberProcedure = "/api.v1.group.Service/AddMember"
	// ServiceRemoveMemberProcedure is the fully-qualified name of the Service's RemoveMember RPC.
	ServiceRemoveMemberProcedure = "/api.v1.group.Service/RemoveMember"
	// ServiceListMembersProcedure is the fully-qualified name of the Service's ListMembers RPC.
	ServiceListMembersProcedure = "/api.v1.group.Service/ListMembers"
	// ServiceListGroupsForMemberProcedure is the fully-qualified name of the Service's
	// ListGroupsForMember RPC.
	ServiceListGroupsForMemberProcedure = "/api.v1.group.Service/ListGroupsForMember"
)

// ServiceClient is a client for the api.v1.group.Service service.
type ServiceClient interface {
	// Create a new group
	Create(context.Context, *connect_go.Request[group.CreateRequest]) (*connect_go.Response[group.CreateResponse], error)
	// Delete group
	Delete(context.Context, *connect_go.Request[group.DeleteRequest]) (*connect_go.Response[group.DeleteResponse], error)
	// List groups
	List(context.Context, *connect_go.Request[group.ListRequest]) (*connect_go.Response[group.ListResponse], error)
	// Update group
	Update(context.Context, *connect_go.Request[group.UpdateRequest]) (*connect_go.Response[group.UpdateResponse], error)
	// Get group
	Get(context.Context, *connect_go.Request[group.GetRequest]) (*connect_go.Response[group.GetResponse], error)
	// Add a member to a group
	AddMember(context.Context, *connect_go.Request[group.AddMemberRequest]) (*connect_go.Response[group.AddMemberResponse], error)
	// Remove member from Group
	RemoveMember(context.Context, *connect_go.Request[group.RemoveMemberRequest]) (*connect_go.Response[group.RemoveMemberResponse], error)
	// Get Group Members
	ListMembers(context.Context, *connect_go.Request[group.ListMembersRequest]) (*connect_go.Response[group.ListMembersResponse], error)
	// Get Groups
	ListGroupsForMember(context.Context, *connect_go.Request[group.ListGroupsForMemberRequest]) (*connect_go.Response[group.ListGroupsForMemberResponse], error)
}

// NewServiceClient constructs a client for the api.v1.group.Service service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) ServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &serviceClient{
		create: connect_go.NewClient[group.CreateRequest, group.CreateResponse](
			httpClient,
			baseURL+ServiceCreateProcedure,
			opts...,
		),
		delete: connect_go.NewClient[group.DeleteRequest, group.DeleteResponse](
			httpClient,
			baseURL+ServiceDeleteProcedure,
			opts...,
		),
		list: connect_go.NewClient[group.ListRequest, group.ListResponse](
			httpClient,
			baseURL+ServiceListProcedure,
			opts...,
		),
		update: connect_go.NewClient[group.UpdateRequest, group.UpdateResponse](
			httpClient,
			baseURL+ServiceUpdateProcedure,
			opts...,
		),
		get: connect_go.NewClient[group.GetRequest, group.GetResponse](
			httpClient,
			baseURL+ServiceGetProcedure,
			opts...,
		),
		addMember: connect_go.NewClient[group.AddMemberRequest, group.AddMemberResponse](
			httpClient,
			baseURL+ServiceAddMemberProcedure,
			opts...,
		),
		removeMember: connect_go.NewClient[group.RemoveMemberRequest, group.RemoveMemberResponse](
			httpClient,
			baseURL+ServiceRemoveMemberProcedure,
			opts...,
		),
		listMembers: connect_go.NewClient[group.ListMembersRequest, group.ListMembersResponse](
			httpClient,
			baseURL+ServiceListMembersProcedure,
			opts...,
		),
		listGroupsForMember: connect_go.NewClient[group.ListGroupsForMemberRequest, group.ListGroupsForMemberResponse](
			httpClient,
			baseURL+ServiceListGroupsForMemberProcedure,
			opts...,
		),
	}
}

// serviceClient implements ServiceClient.
type serviceClient struct {
	create              *connect_go.Client[group.CreateRequest, group.CreateResponse]
	delete              *connect_go.Client[group.DeleteRequest, group.DeleteResponse]
	list                *connect_go.Client[group.ListRequest, group.ListResponse]
	update              *connect_go.Client[group.UpdateRequest, group.UpdateResponse]
	get                 *connect_go.Client[group.GetRequest, group.GetResponse]
	addMember           *connect_go.Client[group.AddMemberRequest, group.AddMemberResponse]
	removeMember        *connect_go.Client[group.RemoveMemberRequest, group.RemoveMemberResponse]
	listMembers         *connect_go.Client[group.ListMembersRequest, group.ListMembersResponse]
	listGroupsForMember *connect_go.Client[group.ListGroupsForMemberRequest, group.ListGroupsForMemberResponse]
}

// Create calls api.v1.group.Service.Create.
func (c *serviceClient) Create(ctx context.Context, req *connect_go.Request[group.CreateRequest]) (*connect_go.Response[group.CreateResponse], error) {
	return c.create.CallUnary(ctx, req)
}

// Delete calls api.v1.group.Service.Delete.
func (c *serviceClient) Delete(ctx context.Context, req *connect_go.Request[group.DeleteRequest]) (*connect_go.Response[group.DeleteResponse], error) {
	return c.delete.CallUnary(ctx, req)
}

// List calls api.v1.group.Service.List.
func (c *serviceClient) List(ctx context.Context, req *connect_go.Request[group.ListRequest]) (*connect_go.Response[group.ListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// Update calls api.v1.group.Service.Update.
func (c *serviceClient) Update(ctx context.Context, req *connect_go.Request[group.UpdateRequest]) (*connect_go.Response[group.UpdateResponse], error) {
	return c.update.CallUnary(ctx, req)
}

// Get calls api.v1.group.Service.Get.
func (c *serviceClient) Get(ctx context.Context, req *connect_go.Request[group.GetRequest]) (*connect_go.Response[group.GetResponse], error) {
	return c.get.CallUnary(ctx, req)
}

// AddMember calls api.v1.group.Service.AddMember.
func (c *serviceClient) AddMember(ctx context.Context, req *connect_go.Request[group.AddMemberRequest]) (*connect_go.Response[group.AddMemberResponse], error) {
	return c.addMember.CallUnary(ctx, req)
}

// RemoveMember calls api.v1.group.Service.RemoveMember.
func (c *serviceClient) RemoveMember(ctx context.Context, req *connect_go.Request[group.RemoveMemberRequest]) (*connect_go.Response[group.RemoveMemberResponse], error) {
	return c.removeMember.CallUnary(ctx, req)
}

// ListMembers calls api.v1.group.Service.ListMembers.
func (c *serviceClient) ListMembers(ctx context.Context, req *connect_go.Request[group.ListMembersRequest]) (*connect_go.Response[group.ListMembersResponse], error) {
	return c.listMembers.CallUnary(ctx, req)
}

// ListGroupsForMember calls api.v1.group.Service.ListGroupsForMember.
func (c *serviceClient) ListGroupsForMember(ctx context.Context, req *connect_go.Request[group.ListGroupsForMemberRequest]) (*connect_go.Response[group.ListGroupsForMemberResponse], error) {
	return c.listGroupsForMember.CallUnary(ctx, req)
}

// ServiceHandler is an implementation of the api.v1.group.Service service.
type ServiceHandler interface {
	// Create a new group
	Create(context.Context, *connect_go.Request[group.CreateRequest]) (*connect_go.Response[group.CreateResponse], error)
	// Delete group
	Delete(context.Context, *connect_go.Request[group.DeleteRequest]) (*connect_go.Response[group.DeleteResponse], error)
	// List groups
	List(context.Context, *connect_go.Request[group.ListRequest]) (*connect_go.Response[group.ListResponse], error)
	// Update group
	Update(context.Context, *connect_go.Request[group.UpdateRequest]) (*connect_go.Response[group.UpdateResponse], error)
	// Get group
	Get(context.Context, *connect_go.Request[group.GetRequest]) (*connect_go.Response[group.GetResponse], error)
	// Add a member to a group
	AddMember(context.Context, *connect_go.Request[group.AddMemberRequest]) (*connect_go.Response[group.AddMemberResponse], error)
	// Remove member from Group
	RemoveMember(context.Context, *connect_go.Request[group.RemoveMemberRequest]) (*connect_go.Response[group.RemoveMemberResponse], error)
	// Get Group Members
	ListMembers(context.Context, *connect_go.Request[group.ListMembersRequest]) (*connect_go.Response[group.ListMembersResponse], error)
	// Get Groups
	ListGroupsForMember(context.Context, *connect_go.Request[group.ListGroupsForMemberRequest]) (*connect_go.Response[group.ListGroupsForMemberResponse], error)
}

// NewServiceHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewServiceHandler(svc ServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	serviceCreateHandler := connect_go.NewUnaryHandler(
		ServiceCreateProcedure,
		svc.Create,
		opts...,
	)
	serviceDeleteHandler := connect_go.NewUnaryHandler(
		ServiceDeleteProcedure,
		svc.Delete,
		opts...,
	)
	serviceListHandler := connect_go.NewUnaryHandler(
		ServiceListProcedure,
		svc.List,
		opts...,
	)
	serviceUpdateHandler := connect_go.NewUnaryHandler(
		ServiceUpdateProcedure,
		svc.Update,
		opts...,
	)
	serviceGetHandler := connect_go.NewUnaryHandler(
		ServiceGetProcedure,
		svc.Get,
		opts...,
	)
	serviceAddMemberHandler := connect_go.NewUnaryHandler(
		ServiceAddMemberProcedure,
		svc.AddMember,
		opts...,
	)
	serviceRemoveMemberHandler := connect_go.NewUnaryHandler(
		ServiceRemoveMemberProcedure,
		svc.RemoveMember,
		opts...,
	)
	serviceListMembersHandler := connect_go.NewUnaryHandler(
		ServiceListMembersProcedure,
		svc.ListMembers,
		opts...,
	)
	serviceListGroupsForMemberHandler := connect_go.NewUnaryHandler(
		ServiceListGroupsForMemberProcedure,
		svc.ListGroupsForMember,
		opts...,
	)
	return "/api.v1.group.Service/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ServiceCreateProcedure:
			serviceCreateHandler.ServeHTTP(w, r)
		case ServiceDeleteProcedure:
			serviceDeleteHandler.ServeHTTP(w, r)
		case ServiceListProcedure:
			serviceListHandler.ServeHTTP(w, r)
		case ServiceUpdateProcedure:
			serviceUpdateHandler.ServeHTTP(w, r)
		case ServiceGetProcedure:
			serviceGetHandler.ServeHTTP(w, r)
		case ServiceAddMemberProcedure:
			serviceAddMemberHandler.ServeHTTP(w, r)
		case ServiceRemoveMemberProcedure:
			serviceRemoveMemberHandler.ServeHTTP(w, r)
		case ServiceListMembersProcedure:
			serviceListMembersHandler.ServeHTTP(w, r)
		case ServiceListGroupsForMemberProcedure:
			serviceListGroupsForMemberHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedServiceHandler struct{}

func (UnimplementedServiceHandler) Create(context.Context, *connect_go.Request[group.CreateRequest]) (*connect_go.Response[group.CreateResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.v1.group.Service.Create is not implemented"))
}

func (UnimplementedServiceHandler) Delete(context.Context, *connect_go.Request[group.DeleteRequest]) (*connect_go.Response[group.DeleteResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.v1.group.Service.Delete is not implemented"))
}

func (UnimplementedServiceHandler) List(context.Context, *connect_go.Request[group.ListRequest]) (*connect_go.Response[group.ListResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.v1.group.Service.List is not implemented"))
}

func (UnimplementedServiceHandler) Update(context.Context, *connect_go.Request[group.UpdateRequest]) (*connect_go.Response[group.UpdateResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.v1.group.Service.Update is not implemented"))
}

func (UnimplementedServiceHandler) Get(context.Context, *connect_go.Request[group.GetRequest]) (*connect_go.Response[group.GetResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.v1.group.Service.Get is not implemented"))
}

func (UnimplementedServiceHandler) AddMember(context.Context, *connect_go.Request[group.AddMemberRequest]) (*connect_go.Response[group.AddMemberResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.v1.group.Service.AddMember is not implemented"))
}

func (UnimplementedServiceHandler) RemoveMember(context.Context, *connect_go.Request[group.RemoveMemberRequest]) (*connect_go.Response[group.RemoveMemberResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.v1.group.Service.RemoveMember is not implemented"))
}

func (UnimplementedServiceHandler) ListMembers(context.Context, *connect_go.Request[group.ListMembersRequest]) (*connect_go.Response[group.ListMembersResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.v1.group.Service.ListMembers is not implemented"))
}

func (UnimplementedServiceHandler) ListGroupsForMember(context.Context, *connect_go.Request[group.ListGroupsForMemberRequest]) (*connect_go.Response[group.ListGroupsForMemberResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.v1.group.Service.ListGroupsForMember is not implemented"))
}
