// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: v1alpha2/generated.proto

package v1alpha2

import (
	v2 "github.com/rigdev/rig-go-api/k8s.io/api/autoscaling/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CapsuleInterface struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port      int32                   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Liveness  *InterfaceProbe         `protobuf:"bytes,3,opt,name=liveness,proto3" json:"liveness,omitempty"`
	Readiness *InterfaceProbe         `protobuf:"bytes,4,opt,name=readiness,proto3" json:"readiness,omitempty"`
	Public    *CapsulePublicInterface `protobuf:"bytes,5,opt,name=public,proto3" json:"public,omitempty"`
	Routes    []*HostRoute            `protobuf:"bytes,6,rep,name=routes,proto3" json:"routes,omitempty"`
}

func (x *CapsuleInterface) Reset() {
	*x = CapsuleInterface{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha2_generated_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CapsuleInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapsuleInterface) ProtoMessage() {}

func (x *CapsuleInterface) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha2_generated_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapsuleInterface.ProtoReflect.Descriptor instead.
func (*CapsuleInterface) Descriptor() ([]byte, []int) {
	return file_v1alpha2_generated_proto_rawDescGZIP(), []int{0}
}

func (x *CapsuleInterface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CapsuleInterface) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *CapsuleInterface) GetLiveness() *InterfaceProbe {
	if x != nil {
		return x.Liveness
	}
	return nil
}

func (x *CapsuleInterface) GetReadiness() *InterfaceProbe {
	if x != nil {
		return x.Readiness
	}
	return nil
}

func (x *CapsuleInterface) GetPublic() *CapsulePublicInterface {
	if x != nil {
		return x.Public
	}
	return nil
}

func (x *CapsuleInterface) GetRoutes() []*HostRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

type InterfaceProbe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string              `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Tcp  bool                `protobuf:"varint,2,opt,name=tcp,proto3" json:"tcp,omitempty"`
	Grpc *InterfaceGRPCProbe `protobuf:"bytes,3,opt,name=grpc,proto3" json:"grpc,omitempty"`
}

func (x *InterfaceProbe) Reset() {
	*x = InterfaceProbe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha2_generated_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterfaceProbe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceProbe) ProtoMessage() {}

func (x *InterfaceProbe) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha2_generated_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceProbe.ProtoReflect.Descriptor instead.
func (*InterfaceProbe) Descriptor() ([]byte, []int) {
	return file_v1alpha2_generated_proto_rawDescGZIP(), []int{1}
}

func (x *InterfaceProbe) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *InterfaceProbe) GetTcp() bool {
	if x != nil {
		return x.Tcp
	}
	return false
}

func (x *InterfaceProbe) GetGrpc() *InterfaceGRPCProbe {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type InterfaceGRPCProbe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Enabled bool   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (x *InterfaceGRPCProbe) Reset() {
	*x = InterfaceGRPCProbe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha2_generated_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterfaceGRPCProbe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceGRPCProbe) ProtoMessage() {}

func (x *InterfaceGRPCProbe) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha2_generated_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceGRPCProbe.ProtoReflect.Descriptor instead.
func (*InterfaceGRPCProbe) Descriptor() ([]byte, []int) {
	return file_v1alpha2_generated_proto_rawDescGZIP(), []int{2}
}

func (x *InterfaceGRPCProbe) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *InterfaceGRPCProbe) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type CapsulePublicInterface struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ingress      *CapsuleInterfaceIngress      `protobuf:"bytes,1,opt,name=ingress,proto3" json:"ingress,omitempty"`
	LoadBalancer *CapsuleInterfaceLoadBalancer `protobuf:"bytes,2,opt,name=loadBalancer,proto3" json:"loadBalancer,omitempty"`
}

func (x *CapsulePublicInterface) Reset() {
	*x = CapsulePublicInterface{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha2_generated_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CapsulePublicInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapsulePublicInterface) ProtoMessage() {}

func (x *CapsulePublicInterface) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha2_generated_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapsulePublicInterface.ProtoReflect.Descriptor instead.
func (*CapsulePublicInterface) Descriptor() ([]byte, []int) {
	return file_v1alpha2_generated_proto_rawDescGZIP(), []int{3}
}

func (x *CapsulePublicInterface) GetIngress() *CapsuleInterfaceIngress {
	if x != nil {
		return x.Ingress
	}
	return nil
}

func (x *CapsulePublicInterface) GetLoadBalancer() *CapsuleInterfaceLoadBalancer {
	if x != nil {
		return x.LoadBalancer
	}
	return nil
}

type CapsuleInterfaceIngress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host  string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Paths []string `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
}

func (x *CapsuleInterfaceIngress) Reset() {
	*x = CapsuleInterfaceIngress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha2_generated_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CapsuleInterfaceIngress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapsuleInterfaceIngress) ProtoMessage() {}

func (x *CapsuleInterfaceIngress) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha2_generated_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapsuleInterfaceIngress.ProtoReflect.Descriptor instead.
func (*CapsuleInterfaceIngress) Descriptor() ([]byte, []int) {
	return file_v1alpha2_generated_proto_rawDescGZIP(), []int{4}
}

func (x *CapsuleInterfaceIngress) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *CapsuleInterfaceIngress) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type CapsuleInterfaceLoadBalancer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port int32 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *CapsuleInterfaceLoadBalancer) Reset() {
	*x = CapsuleInterfaceLoadBalancer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha2_generated_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CapsuleInterfaceLoadBalancer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapsuleInterfaceLoadBalancer) ProtoMessage() {}

func (x *CapsuleInterfaceLoadBalancer) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha2_generated_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapsuleInterfaceLoadBalancer.ProtoReflect.Descriptor instead.
func (*CapsuleInterfaceLoadBalancer) Descriptor() ([]byte, []int) {
	return file_v1alpha2_generated_proto_rawDescGZIP(), []int{5}
}

func (x *CapsuleInterfaceLoadBalancer) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type HostRoute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Host        string            `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Paths       []*HTTPPathRoute  `protobuf:"bytes,3,rep,name=paths,proto3" json:"paths,omitempty"`
	Annotations map[string]string `protobuf:"bytes,4,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *HostRoute) Reset() {
	*x = HostRoute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha2_generated_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostRoute) ProtoMessage() {}

func (x *HostRoute) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha2_generated_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostRoute.ProtoReflect.Descriptor instead.
func (*HostRoute) Descriptor() ([]byte, []int) {
	return file_v1alpha2_generated_proto_rawDescGZIP(), []int{6}
}

func (x *HostRoute) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HostRoute) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *HostRoute) GetPaths() []*HTTPPathRoute {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *HostRoute) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type HTTPPathRoute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path  string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Match string `protobuf:"bytes,2,opt,name=match,proto3" json:"match,omitempty"`
}

func (x *HTTPPathRoute) Reset() {
	*x = HTTPPathRoute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha2_generated_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HTTPPathRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPPathRoute) ProtoMessage() {}

func (x *HTTPPathRoute) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha2_generated_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPPathRoute.ProtoReflect.Descriptor instead.
func (*HTTPPathRoute) Descriptor() ([]byte, []int) {
	return file_v1alpha2_generated_proto_rawDescGZIP(), []int{7}
}

func (x *HTTPPathRoute) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HTTPPathRoute) GetMatch() string {
	if x != nil {
		return x.Match
	}
	return ""
}

type Instances struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min uint32 `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max uint32 `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *Instances) Reset() {
	*x = Instances{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha2_generated_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Instances) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instances) ProtoMessage() {}

func (x *Instances) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha2_generated_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instances.ProtoReflect.Descriptor instead.
func (*Instances) Descriptor() ([]byte, []int) {
	return file_v1alpha2_generated_proto_rawDescGZIP(), []int{8}
}

func (x *Instances) GetMin() uint32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Instances) GetMax() uint32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type CPUTarget struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Utilization uint32 `protobuf:"varint,1,opt,name=utilization,proto3" json:"utilization,omitempty"`
}

func (x *CPUTarget) Reset() {
	*x = CPUTarget{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha2_generated_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CPUTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUTarget) ProtoMessage() {}

func (x *CPUTarget) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha2_generated_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUTarget.ProtoReflect.Descriptor instead.
func (*CPUTarget) Descriptor() ([]byte, []int) {
	return file_v1alpha2_generated_proto_rawDescGZIP(), []int{9}
}

func (x *CPUTarget) GetUtilization() uint32 {
	if x != nil {
		return x.Utilization
	}
	return 0
}

type CustomMetric struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceMetric *InstanceMetric `protobuf:"bytes,1,opt,name=instanceMetric,proto3" json:"instanceMetric,omitempty"`
	ObjectMetric   *ObjectMetric   `protobuf:"bytes,2,opt,name=objectMetric,proto3" json:"objectMetric,omitempty"`
}

func (x *CustomMetric) Reset() {
	*x = CustomMetric{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha2_generated_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomMetric) ProtoMessage() {}

func (x *CustomMetric) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha2_generated_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomMetric.ProtoReflect.Descriptor instead.
func (*CustomMetric) Descriptor() ([]byte, []int) {
	return file_v1alpha2_generated_proto_rawDescGZIP(), []int{10}
}

func (x *CustomMetric) GetInstanceMetric() *InstanceMetric {
	if x != nil {
		return x.InstanceMetric
	}
	return nil
}

func (x *CustomMetric) GetObjectMetric() *ObjectMetric {
	if x != nil {
		return x.ObjectMetric
	}
	return nil
}

type InstanceMetric struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MetricName   string            `protobuf:"bytes,1,opt,name=metricName,proto3" json:"metricName,omitempty"`
	MatchLabels  map[string]string `protobuf:"bytes,2,rep,name=matchLabels,proto3" json:"matchLabels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	AverageValue string            `protobuf:"bytes,3,opt,name=averageValue,proto3" json:"averageValue,omitempty"`
}

func (x *InstanceMetric) Reset() {
	*x = InstanceMetric{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha2_generated_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstanceMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceMetric) ProtoMessage() {}

func (x *InstanceMetric) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha2_generated_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceMetric.ProtoReflect.Descriptor instead.
func (*InstanceMetric) Descriptor() ([]byte, []int) {
	return file_v1alpha2_generated_proto_rawDescGZIP(), []int{11}
}

func (x *InstanceMetric) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *InstanceMetric) GetMatchLabels() map[string]string {
	if x != nil {
		return x.MatchLabels
	}
	return nil
}

func (x *InstanceMetric) GetAverageValue() string {
	if x != nil {
		return x.AverageValue
	}
	return ""
}

type ObjectMetric struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MetricName      string                          `protobuf:"bytes,1,opt,name=metricName,proto3" json:"metricName,omitempty"`
	MatchLabels     map[string]string               `protobuf:"bytes,2,rep,name=matchLabels,proto3" json:"matchLabels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	AverageValue    string                          `protobuf:"bytes,3,opt,name=averageValue,proto3" json:"averageValue,omitempty"`
	Value           string                          `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	ObjectReference *v2.CrossVersionObjectReference `protobuf:"bytes,5,opt,name=objectReference,proto3" json:"objectReference,omitempty"`
}

func (x *ObjectMetric) Reset() {
	*x = ObjectMetric{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha2_generated_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectMetric) ProtoMessage() {}

func (x *ObjectMetric) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha2_generated_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectMetric.ProtoReflect.Descriptor instead.
func (*ObjectMetric) Descriptor() ([]byte, []int) {
	return file_v1alpha2_generated_proto_rawDescGZIP(), []int{12}
}

func (x *ObjectMetric) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *ObjectMetric) GetMatchLabels() map[string]string {
	if x != nil {
		return x.MatchLabels
	}
	return nil
}

func (x *ObjectMetric) GetAverageValue() string {
	if x != nil {
		return x.AverageValue
	}
	return ""
}

func (x *ObjectMetric) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ObjectMetric) GetObjectReference() *v2.CrossVersionObjectReference {
	if x != nil {
		return x.ObjectReference
	}
	return nil
}

type VerticalScale struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cpu    *ResourceLimits  `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory *ResourceLimits  `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Gpu    *ResourceRequest `protobuf:"bytes,3,opt,name=gpu,proto3" json:"gpu,omitempty"`
}

func (x *VerticalScale) Reset() {
	*x = VerticalScale{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha2_generated_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerticalScale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerticalScale) ProtoMessage() {}

func (x *VerticalScale) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha2_generated_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerticalScale.ProtoReflect.Descriptor instead.
func (*VerticalScale) Descriptor() ([]byte, []int) {
	return file_v1alpha2_generated_proto_rawDescGZIP(), []int{13}
}

func (x *VerticalScale) GetCpu() *ResourceLimits {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *VerticalScale) GetMemory() *ResourceLimits {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *VerticalScale) GetGpu() *ResourceRequest {
	if x != nil {
		return x.Gpu
	}
	return nil
}

type ResourceLimits struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request string `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Limit   string `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha2_generated_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha2_generated_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_v1alpha2_generated_proto_rawDescGZIP(), []int{14}
}

func (x *ResourceLimits) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *ResourceLimits) GetLimit() string {
	if x != nil {
		return x.Limit
	}
	return ""
}

type ResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request string `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *ResourceRequest) Reset() {
	*x = ResourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha2_generated_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequest) ProtoMessage() {}

func (x *ResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha2_generated_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequest.ProtoReflect.Descriptor instead.
func (*ResourceRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha2_generated_proto_rawDescGZIP(), []int{15}
}

func (x *ResourceRequest) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

type CronJob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name           string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Schedule       string      `protobuf:"bytes,2,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Url            *URL        `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Command        *JobCommand `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	MaxRetries     uint64      `protobuf:"varint,5,opt,name=maxRetries,proto3" json:"maxRetries,omitempty"`
	TimeoutSeconds uint64      `protobuf:"varint,6,opt,name=timeoutSeconds,proto3" json:"timeoutSeconds,omitempty"`
}

func (x *CronJob) Reset() {
	*x = CronJob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha2_generated_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CronJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronJob) ProtoMessage() {}

func (x *CronJob) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha2_generated_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronJob.ProtoReflect.Descriptor instead.
func (*CronJob) Descriptor() ([]byte, []int) {
	return file_v1alpha2_generated_proto_rawDescGZIP(), []int{16}
}

func (x *CronJob) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CronJob) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *CronJob) GetUrl() *URL {
	if x != nil {
		return x.Url
	}
	return nil
}

func (x *CronJob) GetCommand() *JobCommand {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *CronJob) GetMaxRetries() uint64 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *CronJob) GetTimeoutSeconds() uint64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type URL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port            uint32            `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Path            string            `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	QueryParameters map[string]string `protobuf:"bytes,3,rep,name=queryParameters,proto3" json:"queryParameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *URL) Reset() {
	*x = URL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha2_generated_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URL) ProtoMessage() {}

func (x *URL) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha2_generated_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URL.ProtoReflect.Descriptor instead.
func (*URL) Descriptor() ([]byte, []int) {
	return file_v1alpha2_generated_proto_rawDescGZIP(), []int{17}
}

func (x *URL) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *URL) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *URL) GetQueryParameters() map[string]string {
	if x != nil {
		return x.QueryParameters
	}
	return nil
}

type JobCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command string   `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args    []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *JobCommand) Reset() {
	*x = JobCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha2_generated_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobCommand) ProtoMessage() {}

func (x *JobCommand) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha2_generated_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobCommand.ProtoReflect.Descriptor instead.
func (*JobCommand) Descriptor() ([]byte, []int) {
	return file_v1alpha2_generated_proto_rawDescGZIP(), []int{18}
}

func (x *JobCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *JobCommand) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type CapsuleScale struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Horizontal *HorizontalScale `protobuf:"bytes,1,opt,name=horizontal,proto3" json:"horizontal,omitempty"`
	Vertical   *VerticalScale   `protobuf:"bytes,2,opt,name=vertical,proto3" json:"vertical,omitempty"`
}

func (x *CapsuleScale) Reset() {
	*x = CapsuleScale{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha2_generated_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CapsuleScale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapsuleScale) ProtoMessage() {}

func (x *CapsuleScale) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha2_generated_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapsuleScale.ProtoReflect.Descriptor instead.
func (*CapsuleScale) Descriptor() ([]byte, []int) {
	return file_v1alpha2_generated_proto_rawDescGZIP(), []int{19}
}

func (x *CapsuleScale) GetHorizontal() *HorizontalScale {
	if x != nil {
		return x.Horizontal
	}
	return nil
}

func (x *CapsuleScale) GetVertical() *VerticalScale {
	if x != nil {
		return x.Vertical
	}
	return nil
}

type HorizontalScale struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Instances     *Instances      `protobuf:"bytes,1,opt,name=instances,proto3" json:"instances,omitempty"`
	CpuTarget     *CPUTarget      `protobuf:"bytes,2,opt,name=cpuTarget,proto3" json:"cpuTarget,omitempty"`
	CustomMetrics []*CustomMetric `protobuf:"bytes,3,rep,name=customMetrics,proto3" json:"customMetrics,omitempty"`
}

func (x *HorizontalScale) Reset() {
	*x = HorizontalScale{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha2_generated_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HorizontalScale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HorizontalScale) ProtoMessage() {}

func (x *HorizontalScale) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha2_generated_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HorizontalScale.ProtoReflect.Descriptor instead.
func (*HorizontalScale) Descriptor() ([]byte, []int) {
	return file_v1alpha2_generated_proto_rawDescGZIP(), []int{20}
}

func (x *HorizontalScale) GetInstances() *Instances {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *HorizontalScale) GetCpuTarget() *CPUTarget {
	if x != nil {
		return x.CpuTarget
	}
	return nil
}

func (x *HorizontalScale) GetCustomMetrics() []*CustomMetric {
	if x != nil {
		return x.CustomMetrics
	}
	return nil
}

var File_v1alpha2_generated_proto protoreflect.FileDescriptor

var file_v1alpha2_generated_proto_rawDesc = []byte{
	0x0a, 0x18, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x32, 0x1a, 0x29, 0x6b, 0x38, 0x73, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x61, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x2f, 0x76, 0x32, 0x2f,
	0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x8f, 0x02, 0x0a, 0x10, 0x43, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x34, 0x0a, 0x08,
	0x6c, 0x69, 0x76, 0x65, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x52, 0x08, 0x6c, 0x69, 0x76, 0x65, 0x6e, 0x65,
	0x73, 0x73, 0x12, 0x36, 0x0a, 0x09, 0x72, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32,
	0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x52,
	0x09, 0x72, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x38, 0x0a, 0x06, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x32, 0x2e, 0x43, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x06, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x12, 0x2b, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x2e,
	0x48, 0x6f, 0x73, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x73, 0x22, 0x68, 0x0a, 0x0e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x50, 0x72,
	0x6f, 0x62, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x63, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x74, 0x63, 0x70, 0x12, 0x30, 0x0a, 0x04, 0x67, 0x72, 0x70,
	0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x32, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x47, 0x52, 0x50, 0x43,
	0x50, 0x72, 0x6f, 0x62, 0x65, 0x52, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x48, 0x0a, 0x12, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x47, 0x52, 0x50, 0x43, 0x50, 0x72, 0x6f, 0x62,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x64, 0x22, 0xa1, 0x01, 0x0a, 0x16, 0x43, 0x61, 0x70, 0x73, 0x75, 0x6c,
	0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x12, 0x3b, 0x0a, 0x07, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x2e, 0x43, 0x61, 0x70,
	0x73, 0x75, 0x6c, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x4a, 0x0a,
	0x0c, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x2e, 0x43,
	0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x4c,
	0x6f, 0x61, 0x64, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x52, 0x0c, 0x6c, 0x6f, 0x61,
	0x64, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x22, 0x43, 0x0a, 0x17, 0x43, 0x61, 0x70,
	0x73, 0x75, 0x6c, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x74, 0x68,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x22, 0x32,
	0x0a, 0x1c, 0x43, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x4c, 0x6f, 0x61, 0x64, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f,
	0x72, 0x74, 0x22, 0xe6, 0x01, 0x0a, 0x09, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x68, 0x6f, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x2e, 0x48,
	0x54, 0x54, 0x50, 0x50, 0x61, 0x74, 0x68, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x05, 0x70, 0x61,
	0x74, 0x68, 0x73, 0x12, 0x46, 0x0a, 0x0b, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x32, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x41, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x3e, 0x0a, 0x10, 0x41,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x39, 0x0a, 0x0d, 0x48,
	0x54, 0x54, 0x50, 0x50, 0x61, 0x74, 0x68, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x22, 0x2f, 0x0a, 0x09, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22, 0x2d, 0x0a, 0x09, 0x43, 0x50, 0x55, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x75, 0x74, 0x69, 0x6c, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x75, 0x74, 0x69, 0x6c, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x8c, 0x01, 0x0a, 0x0c, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x40, 0x0a, 0x0e, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x0e, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x3a, 0x0a, 0x0c, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x0c, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x22, 0xe1, 0x01, 0x0a, 0x0e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x4b, 0x0a, 0x0b, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x61, 0x62,
	0x65, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x76, 0x65,
	0x72, 0x61, 0x67, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x3e, 0x0a, 0x10, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xd5, 0x02, 0x0a, 0x0c, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x49, 0x0a, 0x0b, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x27, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x61, 0x62,
	0x65, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x76, 0x65,
	0x72, 0x61, 0x67, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x60, 0x0a, 0x0f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x6b, 0x38, 0x73, 0x2e, 0x69,
	0x6f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x69, 0x6e,
	0x67, 0x2e, 0x76, 0x32, 0x2e, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x52, 0x0f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x1a, 0x3e, 0x0a, 0x10, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x9a, 0x01, 0x0a, 0x0d, 0x56, 0x65, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x53, 0x63,
	0x61, 0x6c, 0x65, 0x12, 0x2a, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x2e, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x52, 0x03, 0x63, 0x70, 0x75, 0x12,
	0x30, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72,
	0x79, 0x12, 0x2b, 0x0a, 0x03, 0x67, 0x70, 0x75, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x03, 0x67, 0x70, 0x75, 0x22, 0x40,
	0x0a, 0x0e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x22, 0x2b, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xd2, 0x01,
	0x0a, 0x07, 0x43, 0x72, 0x6f, 0x6e, 0x4a, 0x6f, 0x62, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x1f, 0x0a, 0x03, 0x75, 0x72, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x32, 0x2e, 0x55, 0x52, 0x4c, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x2e, 0x0a, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x2e, 0x4a, 0x6f, 0x62, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x61,
	0x78, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a,
	0x6d, 0x61, 0x78, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x74, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x73, 0x22, 0xbf, 0x01, 0x0a, 0x03, 0x55, 0x52, 0x4c, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f,
	0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x12, 0x4c, 0x0a, 0x0f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x2e, 0x55, 0x52, 0x4c, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x0f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73,
	0x1a, 0x42, 0x0a, 0x14, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x3a, 0x0a, 0x0a, 0x4a, 0x6f, 0x62, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73,
	0x22, 0x7e, 0x0a, 0x0c, 0x43, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x53, 0x63, 0x61, 0x6c, 0x65,
	0x12, 0x39, 0x0a, 0x0a, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x6f, 0x6e, 0x74, 0x61, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x2e,
	0x48, 0x6f, 0x72, 0x69, 0x7a, 0x6f, 0x6e, 0x74, 0x61, 0x6c, 0x53, 0x63, 0x61, 0x6c, 0x65, 0x52,
	0x0a, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x6f, 0x6e, 0x74, 0x61, 0x6c, 0x12, 0x33, 0x0a, 0x08, 0x76,
	0x65, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x2e, 0x56, 0x65, 0x72, 0x74, 0x69, 0x63, 0x61,
	0x6c, 0x53, 0x63, 0x61, 0x6c, 0x65, 0x52, 0x08, 0x76, 0x65, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c,
	0x22, 0xb5, 0x01, 0x0a, 0x0f, 0x48, 0x6f, 0x72, 0x69, 0x7a, 0x6f, 0x6e, 0x74, 0x61, 0x6c, 0x53,
	0x63, 0x61, 0x6c, 0x65, 0x12, 0x31, 0x0a, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x32, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x09, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x09, 0x63, 0x70, 0x75, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x32, 0x2e, 0x43, 0x50, 0x55, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52,
	0x09, 0x63, 0x70, 0x75, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x3c, 0x0a, 0x0d, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x2e, 0x43, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x0d, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x42, 0x85, 0x01, 0x0a, 0x0c, 0x63, 0x6f, 0x6d,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x42, 0x0e, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x25, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x69, 0x67, 0x64, 0x65, 0x76, 0x2f, 0x72,
	0x69, 0x67, 0x2d, 0x67, 0x6f, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x32, 0xa2, 0x02, 0x03, 0x56, 0x58, 0x58, 0xaa, 0x02, 0x08, 0x56, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x32, 0xca, 0x02, 0x08, 0x56, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0xe2, 0x02,
	0x14, 0x56, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x08, 0x56, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1alpha2_generated_proto_rawDescOnce sync.Once
	file_v1alpha2_generated_proto_rawDescData = file_v1alpha2_generated_proto_rawDesc
)

func file_v1alpha2_generated_proto_rawDescGZIP() []byte {
	file_v1alpha2_generated_proto_rawDescOnce.Do(func() {
		file_v1alpha2_generated_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1alpha2_generated_proto_rawDescData)
	})
	return file_v1alpha2_generated_proto_rawDescData
}

var file_v1alpha2_generated_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_v1alpha2_generated_proto_goTypes = []interface{}{
	(*CapsuleInterface)(nil),               // 0: v1alpha2.CapsuleInterface
	(*InterfaceProbe)(nil),                 // 1: v1alpha2.InterfaceProbe
	(*InterfaceGRPCProbe)(nil),             // 2: v1alpha2.InterfaceGRPCProbe
	(*CapsulePublicInterface)(nil),         // 3: v1alpha2.CapsulePublicInterface
	(*CapsuleInterfaceIngress)(nil),        // 4: v1alpha2.CapsuleInterfaceIngress
	(*CapsuleInterfaceLoadBalancer)(nil),   // 5: v1alpha2.CapsuleInterfaceLoadBalancer
	(*HostRoute)(nil),                      // 6: v1alpha2.HostRoute
	(*HTTPPathRoute)(nil),                  // 7: v1alpha2.HTTPPathRoute
	(*Instances)(nil),                      // 8: v1alpha2.Instances
	(*CPUTarget)(nil),                      // 9: v1alpha2.CPUTarget
	(*CustomMetric)(nil),                   // 10: v1alpha2.CustomMetric
	(*InstanceMetric)(nil),                 // 11: v1alpha2.InstanceMetric
	(*ObjectMetric)(nil),                   // 12: v1alpha2.ObjectMetric
	(*VerticalScale)(nil),                  // 13: v1alpha2.VerticalScale
	(*ResourceLimits)(nil),                 // 14: v1alpha2.ResourceLimits
	(*ResourceRequest)(nil),                // 15: v1alpha2.ResourceRequest
	(*CronJob)(nil),                        // 16: v1alpha2.CronJob
	(*URL)(nil),                            // 17: v1alpha2.URL
	(*JobCommand)(nil),                     // 18: v1alpha2.JobCommand
	(*CapsuleScale)(nil),                   // 19: v1alpha2.CapsuleScale
	(*HorizontalScale)(nil),                // 20: v1alpha2.HorizontalScale
	nil,                                    // 21: v1alpha2.HostRoute.AnnotationsEntry
	nil,                                    // 22: v1alpha2.InstanceMetric.MatchLabelsEntry
	nil,                                    // 23: v1alpha2.ObjectMetric.MatchLabelsEntry
	nil,                                    // 24: v1alpha2.URL.QueryParametersEntry
	(*v2.CrossVersionObjectReference)(nil), // 25: k8s.io.api.autoscaling.v2.CrossVersionObjectReference
}
var file_v1alpha2_generated_proto_depIdxs = []int32{
	1,  // 0: v1alpha2.CapsuleInterface.liveness:type_name -> v1alpha2.InterfaceProbe
	1,  // 1: v1alpha2.CapsuleInterface.readiness:type_name -> v1alpha2.InterfaceProbe
	3,  // 2: v1alpha2.CapsuleInterface.public:type_name -> v1alpha2.CapsulePublicInterface
	6,  // 3: v1alpha2.CapsuleInterface.routes:type_name -> v1alpha2.HostRoute
	2,  // 4: v1alpha2.InterfaceProbe.grpc:type_name -> v1alpha2.InterfaceGRPCProbe
	4,  // 5: v1alpha2.CapsulePublicInterface.ingress:type_name -> v1alpha2.CapsuleInterfaceIngress
	5,  // 6: v1alpha2.CapsulePublicInterface.loadBalancer:type_name -> v1alpha2.CapsuleInterfaceLoadBalancer
	7,  // 7: v1alpha2.HostRoute.paths:type_name -> v1alpha2.HTTPPathRoute
	21, // 8: v1alpha2.HostRoute.annotations:type_name -> v1alpha2.HostRoute.AnnotationsEntry
	11, // 9: v1alpha2.CustomMetric.instanceMetric:type_name -> v1alpha2.InstanceMetric
	12, // 10: v1alpha2.CustomMetric.objectMetric:type_name -> v1alpha2.ObjectMetric
	22, // 11: v1alpha2.InstanceMetric.matchLabels:type_name -> v1alpha2.InstanceMetric.MatchLabelsEntry
	23, // 12: v1alpha2.ObjectMetric.matchLabels:type_name -> v1alpha2.ObjectMetric.MatchLabelsEntry
	25, // 13: v1alpha2.ObjectMetric.objectReference:type_name -> k8s.io.api.autoscaling.v2.CrossVersionObjectReference
	14, // 14: v1alpha2.VerticalScale.cpu:type_name -> v1alpha2.ResourceLimits
	14, // 15: v1alpha2.VerticalScale.memory:type_name -> v1alpha2.ResourceLimits
	15, // 16: v1alpha2.VerticalScale.gpu:type_name -> v1alpha2.ResourceRequest
	17, // 17: v1alpha2.CronJob.url:type_name -> v1alpha2.URL
	18, // 18: v1alpha2.CronJob.command:type_name -> v1alpha2.JobCommand
	24, // 19: v1alpha2.URL.queryParameters:type_name -> v1alpha2.URL.QueryParametersEntry
	20, // 20: v1alpha2.CapsuleScale.horizontal:type_name -> v1alpha2.HorizontalScale
	13, // 21: v1alpha2.CapsuleScale.vertical:type_name -> v1alpha2.VerticalScale
	8,  // 22: v1alpha2.HorizontalScale.instances:type_name -> v1alpha2.Instances
	9,  // 23: v1alpha2.HorizontalScale.cpuTarget:type_name -> v1alpha2.CPUTarget
	10, // 24: v1alpha2.HorizontalScale.customMetrics:type_name -> v1alpha2.CustomMetric
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_v1alpha2_generated_proto_init() }
func file_v1alpha2_generated_proto_init() {
	if File_v1alpha2_generated_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1alpha2_generated_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CapsuleInterface); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha2_generated_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InterfaceProbe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha2_generated_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InterfaceGRPCProbe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha2_generated_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CapsulePublicInterface); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha2_generated_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CapsuleInterfaceIngress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha2_generated_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CapsuleInterfaceLoadBalancer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha2_generated_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostRoute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha2_generated_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HTTPPathRoute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha2_generated_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Instances); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha2_generated_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CPUTarget); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha2_generated_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomMetric); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha2_generated_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstanceMetric); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha2_generated_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectMetric); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha2_generated_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerticalScale); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha2_generated_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceLimits); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha2_generated_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha2_generated_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CronJob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha2_generated_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*URL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha2_generated_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha2_generated_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CapsuleScale); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha2_generated_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HorizontalScale); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1alpha2_generated_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1alpha2_generated_proto_goTypes,
		DependencyIndexes: file_v1alpha2_generated_proto_depIdxs,
		MessageInfos:      file_v1alpha2_generated_proto_msgTypes,
	}.Build()
	File_v1alpha2_generated_proto = out.File
	file_v1alpha2_generated_proto_rawDesc = nil
	file_v1alpha2_generated_proto_goTypes = nil
	file_v1alpha2_generated_proto_depIdxs = nil
}
