// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: operator/api/v1/pipeline/object_status.proto

package pipeline

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObjectType int32

const (
	ObjectType_OBJECT_TYPE_UNSPECIFIED ObjectType = 0
	ObjectType_OBJECT_TYPE_PRIMARY     ObjectType = 1
	ObjectType_OBJECT_TYPE_SECONDARY   ObjectType = 2
	ObjectType_OBJECT_TYPE_POD         ObjectType = 3
)

// Enum value maps for ObjectType.
var (
	ObjectType_name = map[int32]string{
		0: "OBJECT_TYPE_UNSPECIFIED",
		1: "OBJECT_TYPE_PRIMARY",
		2: "OBJECT_TYPE_SECONDARY",
		3: "OBJECT_TYPE_POD",
	}
	ObjectType_value = map[string]int32{
		"OBJECT_TYPE_UNSPECIFIED": 0,
		"OBJECT_TYPE_PRIMARY":     1,
		"OBJECT_TYPE_SECONDARY":   2,
		"OBJECT_TYPE_POD":         3,
	}
)

func (x ObjectType) Enum() *ObjectType {
	p := new(ObjectType)
	*p = x
	return p
}

func (x ObjectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectType) Descriptor() protoreflect.EnumDescriptor {
	return file_operator_api_v1_pipeline_object_status_proto_enumTypes[0].Descriptor()
}

func (ObjectType) Type() protoreflect.EnumType {
	return &file_operator_api_v1_pipeline_object_status_proto_enumTypes[0]
}

func (x ObjectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectType.Descriptor instead.
func (ObjectType) EnumDescriptor() ([]byte, []int) {
	return file_operator_api_v1_pipeline_object_status_proto_rawDescGZIP(), []int{0}
}

type ObjectState int32

const (
	ObjectState_OBJECT_STATE_UNSPECIFIED ObjectState = 0
	ObjectState_OBJECT_STATE_HEALTHY     ObjectState = 1
	ObjectState_OBJECT_STATE_PENDING     ObjectState = 2
	ObjectState_OBJECT_STATE_ERROR       ObjectState = 3
)

// Enum value maps for ObjectState.
var (
	ObjectState_name = map[int32]string{
		0: "OBJECT_STATE_UNSPECIFIED",
		1: "OBJECT_STATE_HEALTHY",
		2: "OBJECT_STATE_PENDING",
		3: "OBJECT_STATE_ERROR",
	}
	ObjectState_value = map[string]int32{
		"OBJECT_STATE_UNSPECIFIED": 0,
		"OBJECT_STATE_HEALTHY":     1,
		"OBJECT_STATE_PENDING":     2,
		"OBJECT_STATE_ERROR":       3,
	}
)

func (x ObjectState) Enum() *ObjectState {
	p := new(ObjectState)
	*p = x
	return p
}

func (x ObjectState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectState) Descriptor() protoreflect.EnumDescriptor {
	return file_operator_api_v1_pipeline_object_status_proto_enumTypes[1].Descriptor()
}

func (ObjectState) Type() protoreflect.EnumType {
	return &file_operator_api_v1_pipeline_object_status_proto_enumTypes[1]
}

func (x ObjectState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectState.Descriptor instead.
func (ObjectState) EnumDescriptor() ([]byte, []int) {
	return file_operator_api_v1_pipeline_object_status_proto_rawDescGZIP(), []int{1}
}

type ObjectStatusChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Capsule string `protobuf:"bytes,1,opt,name=capsule,proto3" json:"capsule,omitempty"`
	// Types that are assignable to Change:
	//
	//	*ObjectStatusChange_Updated
	//	*ObjectStatusChange_Deleted
	//	*ObjectStatusChange_Checkpoint_
	Change isObjectStatusChange_Change `protobuf_oneof:"change"`
}

func (x *ObjectStatusChange) Reset() {
	*x = ObjectStatusChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operator_api_v1_pipeline_object_status_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectStatusChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectStatusChange) ProtoMessage() {}

func (x *ObjectStatusChange) ProtoReflect() protoreflect.Message {
	mi := &file_operator_api_v1_pipeline_object_status_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectStatusChange.ProtoReflect.Descriptor instead.
func (*ObjectStatusChange) Descriptor() ([]byte, []int) {
	return file_operator_api_v1_pipeline_object_status_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectStatusChange) GetCapsule() string {
	if x != nil {
		return x.Capsule
	}
	return ""
}

func (m *ObjectStatusChange) GetChange() isObjectStatusChange_Change {
	if m != nil {
		return m.Change
	}
	return nil
}

func (x *ObjectStatusChange) GetUpdated() *ObjectStatus {
	if x, ok := x.GetChange().(*ObjectStatusChange_Updated); ok {
		return x.Updated
	}
	return nil
}

func (x *ObjectStatusChange) GetDeleted() *ObjectRef {
	if x, ok := x.GetChange().(*ObjectStatusChange_Deleted); ok {
		return x.Deleted
	}
	return nil
}

func (x *ObjectStatusChange) GetCheckpoint() *ObjectStatusChange_Checkpoint {
	if x, ok := x.GetChange().(*ObjectStatusChange_Checkpoint_); ok {
		return x.Checkpoint
	}
	return nil
}

type isObjectStatusChange_Change interface {
	isObjectStatusChange_Change()
}

type ObjectStatusChange_Updated struct {
	Updated *ObjectStatus `protobuf:"bytes,2,opt,name=updated,proto3,oneof"`
}

type ObjectStatusChange_Deleted struct {
	Deleted *ObjectRef `protobuf:"bytes,3,opt,name=deleted,proto3,oneof"`
}

type ObjectStatusChange_Checkpoint_ struct {
	// Checkpoint events indicates that all existing object statuses for
	// this namespace has been sent in the current "watch" session.
	Checkpoint *ObjectStatusChange_Checkpoint `protobuf:"bytes,4,opt,name=checkpoint,proto3,oneof"`
}

func (*ObjectStatusChange_Updated) isObjectStatusChange_Change() {}

func (*ObjectStatusChange_Deleted) isObjectStatusChange_Change() {}

func (*ObjectStatusChange_Checkpoint_) isObjectStatusChange_Change() {}

type ObjectStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectRef  *ObjectRef         `protobuf:"bytes,1,opt,name=object_ref,json=objectRef,proto3" json:"object_ref,omitempty"`
	Type       ObjectType         `protobuf:"varint,2,opt,name=type,proto3,enum=api.v1.pipeline.ObjectType" json:"type,omitempty"`
	Conditions []*ObjectCondition `protobuf:"bytes,3,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Properties map[string]string  `protobuf:"bytes,4,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ObjectStatus) Reset() {
	*x = ObjectStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operator_api_v1_pipeline_object_status_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectStatus) ProtoMessage() {}

func (x *ObjectStatus) ProtoReflect() protoreflect.Message {
	mi := &file_operator_api_v1_pipeline_object_status_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectStatus.ProtoReflect.Descriptor instead.
func (*ObjectStatus) Descriptor() ([]byte, []int) {
	return file_operator_api_v1_pipeline_object_status_proto_rawDescGZIP(), []int{1}
}

func (x *ObjectStatus) GetObjectRef() *ObjectRef {
	if x != nil {
		return x.ObjectRef
	}
	return nil
}

func (x *ObjectStatus) GetType() ObjectType {
	if x != nil {
		return x.Type
	}
	return ObjectType_OBJECT_TYPE_UNSPECIFIED
}

func (x *ObjectStatus) GetConditions() []*ObjectCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *ObjectStatus) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type ObjectCondition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	State     ObjectState            `protobuf:"varint,3,opt,name=state,proto3,enum=api.v1.pipeline.ObjectState" json:"state,omitempty"`
	Message   string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ObjectCondition) Reset() {
	*x = ObjectCondition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operator_api_v1_pipeline_object_status_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectCondition) ProtoMessage() {}

func (x *ObjectCondition) ProtoReflect() protoreflect.Message {
	mi := &file_operator_api_v1_pipeline_object_status_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectCondition.ProtoReflect.Descriptor instead.
func (*ObjectCondition) Descriptor() ([]byte, []int) {
	return file_operator_api_v1_pipeline_object_status_proto_rawDescGZIP(), []int{2}
}

func (x *ObjectCondition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectCondition) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ObjectCondition) GetState() ObjectState {
	if x != nil {
		return x.State
	}
	return ObjectState_OBJECT_STATE_UNSPECIFIED
}

func (x *ObjectCondition) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GVK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group   string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Kind    string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
}

func (x *GVK) Reset() {
	*x = GVK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operator_api_v1_pipeline_object_status_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GVK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GVK) ProtoMessage() {}

func (x *GVK) ProtoReflect() protoreflect.Message {
	mi := &file_operator_api_v1_pipeline_object_status_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GVK.ProtoReflect.Descriptor instead.
func (*GVK) Descriptor() ([]byte, []int) {
	return file_operator_api_v1_pipeline_object_status_proto_rawDescGZIP(), []int{3}
}

func (x *GVK) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GVK) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GVK) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type ObjectRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gvk       *GVK   `protobuf:"bytes,1,opt,name=gvk,proto3" json:"gvk,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ObjectRef) Reset() {
	*x = ObjectRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operator_api_v1_pipeline_object_status_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectRef) ProtoMessage() {}

func (x *ObjectRef) ProtoReflect() protoreflect.Message {
	mi := &file_operator_api_v1_pipeline_object_status_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectRef.ProtoReflect.Descriptor instead.
func (*ObjectRef) Descriptor() ([]byte, []int) {
	return file_operator_api_v1_pipeline_object_status_proto_rawDescGZIP(), []int{4}
}

func (x *ObjectRef) GetGvk() *GVK {
	if x != nil {
		return x.Gvk
	}
	return nil
}

func (x *ObjectRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ObjectRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ObjectStatusChange_Checkpoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ObjectStatusChange_Checkpoint) Reset() {
	*x = ObjectStatusChange_Checkpoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operator_api_v1_pipeline_object_status_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectStatusChange_Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectStatusChange_Checkpoint) ProtoMessage() {}

func (x *ObjectStatusChange_Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_operator_api_v1_pipeline_object_status_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectStatusChange_Checkpoint.ProtoReflect.Descriptor instead.
func (*ObjectStatusChange_Checkpoint) Descriptor() ([]byte, []int) {
	return file_operator_api_v1_pipeline_object_status_proto_rawDescGZIP(), []int{0, 0}
}

var File_operator_api_v1_pipeline_object_status_proto protoreflect.FileDescriptor

var file_operator_api_v1_pipeline_object_status_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x2f, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2f, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x8b, 0x02, 0x0a, 0x12, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x61, 0x70, 0x73, 0x75,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c,
	0x65, 0x12, 0x39, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x69, 0x70, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x48, 0x00, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x36, 0x0a, 0x07,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x66, 0x48, 0x00, 0x52, 0x07, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x12, 0x50, 0x0a, 0x0a, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x1a, 0x0c, 0x0a, 0x0a, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x22, 0xca,
	0x02, 0x0a, 0x0c, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x39, 0x0a, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x69, 0x70,
	0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x66, 0x52,
	0x09, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x66, 0x12, 0x2f, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x40, 0x0a, 0x0a, 0x63,
	0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x4d, 0x0a,
	0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x2d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c,
	0x69, 0x6e, 0x65, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x2e, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x1a, 0x3d, 0x0a, 0x0f,
	0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xae, 0x01, 0x0a, 0x0f,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x32,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x49, 0x0a, 0x03,
	0x47, 0x56, 0x4b, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0x65, 0x0a, 0x09, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x66, 0x12, 0x26, 0x0a, 0x03, 0x67, 0x76, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c,
	0x69, 0x6e, 0x65, 0x2e, 0x47, 0x56, 0x4b, 0x52, 0x03, 0x67, 0x76, 0x6b, 0x12, 0x1c, 0x0a, 0x09,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x2a, 0x72,
	0x0a, 0x0a, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x17,
	0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x4f, 0x42, 0x4a,
	0x45, 0x43, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x52, 0x49, 0x4d, 0x41, 0x52, 0x59,
	0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x53, 0x45, 0x43, 0x4f, 0x4e, 0x44, 0x41, 0x52, 0x59, 0x10, 0x02, 0x12, 0x13, 0x0a,
	0x0f, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x4f, 0x44,
	0x10, 0x03, 0x2a, 0x77, 0x0a, 0x0b, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x1c, 0x0a, 0x18, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x18, 0x0a, 0x14, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x48, 0x45, 0x41, 0x4c, 0x54, 0x48, 0x59, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x4f, 0x42, 0x4a,
	0x45, 0x43, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e,
	0x47, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x42, 0xbd, 0x01, 0x0a, 0x13,
	0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c,
	0x69, 0x6e, 0x65, 0x42, 0x11, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x69, 0x67, 0x64, 0x65, 0x76, 0x2f, 0x72, 0x69, 0x67, 0x2d,
	0x67, 0x6f, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0xa2,
	0x02, 0x03, 0x41, 0x56, 0x50, 0xaa, 0x02, 0x0f, 0x41, 0x70, 0x69, 0x2e, 0x56, 0x31, 0x2e, 0x50,
	0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0xca, 0x02, 0x0f, 0x41, 0x70, 0x69, 0x5c, 0x56, 0x31,
	0x5c, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0xe2, 0x02, 0x1b, 0x41, 0x70, 0x69, 0x5c,
	0x56, 0x31, 0x5c, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x11, 0x41, 0x70, 0x69, 0x3a, 0x3a, 0x56,
	0x31, 0x3a, 0x3a, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_operator_api_v1_pipeline_object_status_proto_rawDescOnce sync.Once
	file_operator_api_v1_pipeline_object_status_proto_rawDescData = file_operator_api_v1_pipeline_object_status_proto_rawDesc
)

func file_operator_api_v1_pipeline_object_status_proto_rawDescGZIP() []byte {
	file_operator_api_v1_pipeline_object_status_proto_rawDescOnce.Do(func() {
		file_operator_api_v1_pipeline_object_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_operator_api_v1_pipeline_object_status_proto_rawDescData)
	})
	return file_operator_api_v1_pipeline_object_status_proto_rawDescData
}

var file_operator_api_v1_pipeline_object_status_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_operator_api_v1_pipeline_object_status_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_operator_api_v1_pipeline_object_status_proto_goTypes = []interface{}{
	(ObjectType)(0),                       // 0: api.v1.pipeline.ObjectType
	(ObjectState)(0),                      // 1: api.v1.pipeline.ObjectState
	(*ObjectStatusChange)(nil),            // 2: api.v1.pipeline.ObjectStatusChange
	(*ObjectStatus)(nil),                  // 3: api.v1.pipeline.ObjectStatus
	(*ObjectCondition)(nil),               // 4: api.v1.pipeline.ObjectCondition
	(*GVK)(nil),                           // 5: api.v1.pipeline.GVK
	(*ObjectRef)(nil),                     // 6: api.v1.pipeline.ObjectRef
	(*ObjectStatusChange_Checkpoint)(nil), // 7: api.v1.pipeline.ObjectStatusChange.Checkpoint
	nil,                                   // 8: api.v1.pipeline.ObjectStatus.PropertiesEntry
	(*timestamppb.Timestamp)(nil),         // 9: google.protobuf.Timestamp
}
var file_operator_api_v1_pipeline_object_status_proto_depIdxs = []int32{
	3,  // 0: api.v1.pipeline.ObjectStatusChange.updated:type_name -> api.v1.pipeline.ObjectStatus
	6,  // 1: api.v1.pipeline.ObjectStatusChange.deleted:type_name -> api.v1.pipeline.ObjectRef
	7,  // 2: api.v1.pipeline.ObjectStatusChange.checkpoint:type_name -> api.v1.pipeline.ObjectStatusChange.Checkpoint
	6,  // 3: api.v1.pipeline.ObjectStatus.object_ref:type_name -> api.v1.pipeline.ObjectRef
	0,  // 4: api.v1.pipeline.ObjectStatus.type:type_name -> api.v1.pipeline.ObjectType
	4,  // 5: api.v1.pipeline.ObjectStatus.conditions:type_name -> api.v1.pipeline.ObjectCondition
	8,  // 6: api.v1.pipeline.ObjectStatus.properties:type_name -> api.v1.pipeline.ObjectStatus.PropertiesEntry
	9,  // 7: api.v1.pipeline.ObjectCondition.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 8: api.v1.pipeline.ObjectCondition.state:type_name -> api.v1.pipeline.ObjectState
	5,  // 9: api.v1.pipeline.ObjectRef.gvk:type_name -> api.v1.pipeline.GVK
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_operator_api_v1_pipeline_object_status_proto_init() }
func file_operator_api_v1_pipeline_object_status_proto_init() {
	if File_operator_api_v1_pipeline_object_status_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_operator_api_v1_pipeline_object_status_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectStatusChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_operator_api_v1_pipeline_object_status_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_operator_api_v1_pipeline_object_status_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectCondition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_operator_api_v1_pipeline_object_status_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GVK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_operator_api_v1_pipeline_object_status_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_operator_api_v1_pipeline_object_status_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectStatusChange_Checkpoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_operator_api_v1_pipeline_object_status_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ObjectStatusChange_Updated)(nil),
		(*ObjectStatusChange_Deleted)(nil),
		(*ObjectStatusChange_Checkpoint_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_operator_api_v1_pipeline_object_status_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_operator_api_v1_pipeline_object_status_proto_goTypes,
		DependencyIndexes: file_operator_api_v1_pipeline_object_status_proto_depIdxs,
		EnumInfos:         file_operator_api_v1_pipeline_object_status_proto_enumTypes,
		MessageInfos:      file_operator_api_v1_pipeline_object_status_proto_msgTypes,
	}.Build()
	File_operator_api_v1_pipeline_object_status_proto = out.File
	file_operator_api_v1_pipeline_object_status_proto_rawDesc = nil
	file_operator_api_v1_pipeline_object_status_proto_goTypes = nil
	file_operator_api_v1_pipeline_object_status_proto_depIdxs = nil
}
